<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGlqxv7k\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGlqxv7k/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGlqxv7k.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGlqxv7k\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGlqxv7k\appProdProjectContainer([
    'container.build_hash' => 'Glqxv7k',
    'container.build_id' => 'e109b225',
    'container.build_time' => 1633881886,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGlqxv7k');
