<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSbktsiu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSbktsiu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSbktsiu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSbktsiu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSbktsiu\appProdProjectContainer([
    'container.build_hash' => 'Sbktsiu',
    'container.build_id' => '6c010f3c',
    'container.build_time' => 1633859263,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSbktsiu');
